### ISSUE TITLE
what Deepfacepath is 

### ISSUE THREAD

**Issue by ineslyl** [HRLTY/TP-GAN#2]
Traceback (most recent call last):
  File "TP_GAN-Mar6FS.py", line 1132, in <module>
    tf.app.run()
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "TP_GAN-Mar6FS.py", line 1128, in main
    sample_dir=FLAGS.sample_dir)
  File "TP_GAN-Mar6FS.py", line 127, in __init__
    self.loadDeepFace(self.DeepFacePath)
  File "TP_GAN-Mar6FS.py", line 866, in loadDeepFace
    logging.error(("File '%s' not found. "), DeepFacePath)

**Comment by HRLTY** [comment]
Please see updated README.

**Comment by HRLTY** [comment]
One version of the file has been uploaded
