### ISSUE TITLE
AttributeError: only_check_args

### ISSUE THREAD

**Issue by ujwalakoriraj** [HRLTY/TP-GAN#25]
I encounter the following long error running the TP_GAN-Mar6FS.py program:

.............

Traceback (most recent call last):

  File "D:\python\projects\reidentification\face_frontalization\frontalization-master\4_TP-GAN-master\TP_GAN-Mar6FS.py", line 1059, in <module>
    tf.compat.v1.app.run()

  File "C:\Users\rajak\anaconda3\envs\deep_learning\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)

  File "C:\Users\rajak\anaconda3\envs\deep_learning\lib\site-packages\absl\app.py", line 295, in run
    flags_parser,

  File "C:\Users\rajak\anaconda3\envs\deep_learning\lib\site-packages\absl\app.py", line 364, in _run_init
    flags_parser=flags_parser,

  File "C:\Users\rajak\anaconda3\envs\deep_learning\lib\site-packages\absl\app.py", line 217, in _register_and_parse_flags_with_usage
    if FLAGS.only_check_args:

  File "C:\Users\rajak\anaconda3\envs\deep_learning\lib\site-packages\absl\flags\_flagvalues.py", line 474, in __getattr__
    raise AttributeError(name)

AttributeError: only_check_args
.............

**Comment by NadiaAmina30** [comment]
Where you able to fix it

**Comment by NadiaAmina30** [comment]
Were you able to fix it?

**Comment by akanksha180497** [comment]
are you able to fix it?

**Comment by ujwalakoriraj** [comment]
No!
